import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import getData from "../api";
import { GetStaticProps } from "next";
import Link from "next/link";

export const getStaticProps: GetStaticProps = async () => {
  const listings = getData();
  return {
    props: {
      listings: listings,
    },
  };
};

export default function Home({ listings }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>galleria</h1>
      <div className={styles.container}>
        {listings.map((listing) => {
          return (
            <Link href={`/listing/${listing.id}`} key={listing.id}>
              <div className={styles.listing}>
                <img
                  className={styles.image}
                  src={`/${listing?.images?.thumbnail}`}
                />
                <div className={styles.authorInfo}>
                  <h2>{listing?.name}</h2>
                  <div className={styles.authorName}>
                    {listing?.artist?.name}
                  </div>
                </div>
              </div>
            </Link>
          );
        })}
      </div>
    </div>
  );
}
