import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import getData from "../api";

export async function getStaticProps() {
  const listings = getData();
  return {
    props: {
      listings: listings,
    },
  };
}

export default function Home({ listings }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>Galleria</h1>
      <div className={styles.container}>
        {listings.map((listing) => {
          return (
            <img
              className={styles.listing}
              key={listing.id}
              src={`/${listing?.images?.thumbnail}`}
            />
          );
        })}
      </div>
    </div>
  );
}
